[package]
name = "liom_parser"
version = "0.1.0"
edition = "2021"
authors = ["Guillaume Dallenne <dallenneguillaume@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
liom_node = { path = "../liom_node" }
liom_token = { path = "../liom_token" }
