name: Dependencies

on:
  schedule:
    - cron: "0 0 1 * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - run: |
          cargo install cargo-outdated
          cargo outdated --exit-code 1
